P          <- Stm+ EOF
Stm        <- IfStm / WhileStm / AssignStm
IfStm      <- 'if' '('^iflpar Expr^ifexpr ')'^ifrpar Body^ifbody
WhileStm   <- 'while' '('^wlpar Expr^wexpr ')'^wrpar Body^wbody
AssignStm  <- Identifier '='^assigneq Expr^assignexpr ';'^assignsemi

Body       <- '{' Stm* '}' / Stm
Expr       <- Bool / Identifier / Number
Bool       <- 'true' / 'false'
Identifier <- [a-zA-Z_][a-zA-Z0-9_]*
Number     <- [1-9][0-9]*

// recovery expressions for the labels declared above

iflpar     <- (!Expr .)*
ifexpr     <- (!(')' / '{') .)*
ifrpar     <- (!Body .)*
assigneq   <- (!Expr .)*
assignexpr <- (!';' .)*
assignsemi <-
