[package]
name = "langlang_serde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
langlang_lib = { path = "../langlang_lib", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
