// Code generated by langlang extract -mode=views; DO NOT EDIT.
// Grammar: /Users/sfriedenberg/eng/repos/langlang/.worktrees/light-rowan/docs/live/assets/examples/json/json.peg

package jsonviews

const (
	_nameID_Array   int32 = 21
	_nameID_Char    int32 = 24
	_nameID_EOF     int32 = 19
	_nameID_EOL     int32 = 34
	_nameID_Escape  int32 = 25
	_nameID_Exp     int32 = 31
	_nameID_Frac    int32 = 30
	_nameID_Hex     int32 = 27
	_nameID_Int     int32 = 29
	_nameID_JSON    int32 = 16
	_nameID_Member  int32 = 32
	_nameID_Number  int32 = 28
	_nameID_Object  int32 = 20
	_nameID_Space   int32 = 33
	_nameID_Spacing int32 = 17
	_nameID_String  int32 = 22
	_nameID_Unicode int32 = 26
	_nameID_Value   int32 = 18
)

// JSON is a read-only view over a JSON node.
// Child references are resolved once at construction time.
type JSON struct {
	t         *tree
	id        NodeID
	_value    NodeID
	_hasValue bool
	_eOF      NodeID
	_hasEOF   bool
}

// String returns the full matched text of this node.
func (v JSON) String() string {
	return v.t.Text(v.id)
}

func newJSON(t *tree, id NodeID) JSON {
	v := JSON{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Value:
				if !v._hasValue {
					v._value = cid
					v._hasValue = true
				}
			case _nameID_EOF:
				if !v._hasEOF {
					v._eOF = cid
					v._hasEOF = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Value:
			v._value = child
			v._hasValue = true
		case _nameID_EOF:
			v._eOF = child
			v._hasEOF = true
		}
	}
	return v
}

// Value returns a view over the Value child.
func (v JSON) Value() (Value, bool) {
	if !v._hasValue {
		return Value{}, false
	}
	return Value{t: v.t, id: v._value}, true
}

// EOF returns the EOF text.
func (v JSON) EOF() string {
	if !v._hasEOF {
		return ""
	}
	return v.t.Text(v._eOF)
}

// Array is a read-only view over a Array node.
// Child references are resolved once at construction time.
type Array struct {
	t      *tree
	id     NodeID
	_value []NodeID
}

// String returns the full matched text of this node.
func (v Array) String() string {
	return v.t.Text(v.id)
}

func newArray(t *tree, id NodeID) Array {
	v := Array{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	mark_value := t.viewMark()
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Value:
				t.viewAppend(cid)
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Value:
			t.viewAppend(child)
		}
	}
	v._value = t.viewSlice(mark_value)
	return v
}

// ValueCount returns the number of Value children.
func (v Array) ValueCount() int {
	return len(v._value)
}

// ValueAt returns a view over the i-th Value child.
func (v Array) ValueAt(i int) Value {
	return Value{t: v.t, id: v._value[i]}
}

// Char is a read-only view over a Char node.
type Char struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v Char) String() string {
	return v.t.Text(v.id)
}

// Escape returns a Escape if this alternative matched.
func (v Char) Escape() (Escape, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Escape) {
		return Escape{}, false
	}
	return newEscape(v.t, child), true
}

// Unicode returns a Unicode if this alternative matched.
func (v Char) Unicode() (Unicode, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Unicode) {
		return Unicode{}, false
	}
	return newUnicode(v.t, child), true
}

// eOF_view is a read-only view over a EOF node.
type eOF_view struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v eOF_view) String() string {
	return v.t.Text(v.id)
}

// eOL_view is a read-only view over a EOL node.
type eOL_view struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v eOL_view) String() string {
	return v.t.Text(v.id)
}

// Escape is a read-only view over a Escape node.
// Child references are resolved once at construction time.
type Escape struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v Escape) String() string {
	return v.t.Text(v.id)
}

func newEscape(t *tree, id NodeID) Escape {
	v := Escape{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// Exp is a read-only view over a Exp node.
// Child references are resolved once at construction time.
type Exp struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v Exp) String() string {
	return v.t.Text(v.id)
}

func newExp(t *tree, id NodeID) Exp {
	v := Exp{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// Frac is a read-only view over a Frac node.
// Child references are resolved once at construction time.
type Frac struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v Frac) String() string {
	return v.t.Text(v.id)
}

func newFrac(t *tree, id NodeID) Frac {
	v := Frac{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// hex_view is a read-only view over a Hex node.
type hex_view struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v hex_view) String() string {
	return v.t.Text(v.id)
}

// Int is a read-only view over a Int node.
type Int struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v Int) String() string {
	return v.t.Text(v.id)
}

// Member is a read-only view over a Member node.
// Child references are resolved once at construction time.
type Member struct {
	t          *tree
	id         NodeID
	_string    NodeID
	_hasString bool
	_value     NodeID
	_hasValue  bool
}

// String returns the full matched text of this node.
func (v Member) String() string {
	return v.t.Text(v.id)
}

func newMember(t *tree, id NodeID) Member {
	v := Member{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_String:
				if !v._hasString {
					v._string = cid
					v._hasString = true
				}
			case _nameID_Value:
				if !v._hasValue {
					v._value = cid
					v._hasValue = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_String:
			v._string = child
			v._hasString = true
		case _nameID_Value:
			v._value = child
			v._hasValue = true
		}
	}
	return v
}

// StringNode returns a view over the String child.
func (v Member) StringNode() (String, bool) {
	if !v._hasString {
		return String{}, false
	}
	return newString(v.t, v._string), true
}

// Value returns a view over the Value child.
func (v Member) Value() (Value, bool) {
	if !v._hasValue {
		return Value{}, false
	}
	return Value{t: v.t, id: v._value}, true
}

// Number is a read-only view over a Number node.
// Child references are resolved once at construction time.
type Number struct {
	t        *tree
	id       NodeID
	_int     NodeID
	_hasInt  bool
	_frac    NodeID
	_hasFrac bool
	_exp     NodeID
	_hasExp  bool
}

// String returns the full matched text of this node.
func (v Number) String() string {
	return v.t.Text(v.id)
}

func newNumber(t *tree, id NodeID) Number {
	v := Number{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Int:
				if !v._hasInt {
					v._int = cid
					v._hasInt = true
				}
			case _nameID_Frac:
				if !v._hasFrac {
					v._frac = cid
					v._hasFrac = true
				}
			case _nameID_Exp:
				if !v._hasExp {
					v._exp = cid
					v._hasExp = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Int:
			v._int = child
			v._hasInt = true
		case _nameID_Frac:
			v._frac = child
			v._hasFrac = true
		case _nameID_Exp:
			v._exp = child
			v._hasExp = true
		}
	}
	return v
}

// Int returns a view over the Int child.
func (v Number) Int() (Int, bool) {
	if !v._hasInt {
		return Int{}, false
	}
	return Int{t: v.t, id: v._int}, true
}

// Frac returns a view over the Frac child.
func (v Number) Frac() (Frac, bool) {
	if !v._hasFrac {
		return Frac{}, false
	}
	return newFrac(v.t, v._frac), true
}

// Exp returns a view over the Exp child.
func (v Number) Exp() (Exp, bool) {
	if !v._hasExp {
		return Exp{}, false
	}
	return newExp(v.t, v._exp), true
}

// Object is a read-only view over a Object node.
// Child references are resolved once at construction time.
type Object struct {
	t       *tree
	id      NodeID
	_member []NodeID
}

// String returns the full matched text of this node.
func (v Object) String() string {
	return v.t.Text(v.id)
}

func newObject(t *tree, id NodeID) Object {
	v := Object{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	mark_member := t.viewMark()
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Member:
				t.viewAppend(cid)
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Member:
			t.viewAppend(child)
		}
	}
	v._member = t.viewSlice(mark_member)
	return v
}

// MemberCount returns the number of Member children.
func (v Object) MemberCount() int {
	return len(v._member)
}

// MemberAt returns a view over the i-th Member child.
func (v Object) MemberAt(i int) Member {
	return newMember(v.t, v._member[i])
}

// space_view is a read-only view over a Space node.
type space_view struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v space_view) String() string {
	return v.t.Text(v.id)
}

// spacing_view is a read-only view over a Spacing node.
type spacing_view struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v spacing_view) String() string {
	return v.t.Text(v.id)
}

// String is a read-only view over a String node.
// Child references are resolved once at construction time.
type String struct {
	t     *tree
	id    NodeID
	_char []NodeID
}

// String returns the full matched text of this node.
func (v String) String() string {
	return v.t.Text(v.id)
}

func newString(t *tree, id NodeID) String {
	v := String{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	mark_char := t.viewMark()
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Char:
				t.viewAppend(cid)
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Char:
			t.viewAppend(child)
		}
	}
	v._char = t.viewSlice(mark_char)
	return v
}

// CharCount returns the number of Char children.
func (v String) CharCount() int {
	return len(v._char)
}

// CharAt returns a view over the i-th Char child.
func (v String) CharAt(i int) Char {
	return Char{t: v.t, id: v._char[i]}
}

// Unicode is a read-only view over a Unicode node.
// Child references are resolved once at construction time.
type Unicode struct {
	t    *tree
	id   NodeID
	_hex []NodeID
}

// String returns the full matched text of this node.
func (v Unicode) String() string {
	return v.t.Text(v.id)
}

func newUnicode(t *tree, id NodeID) Unicode {
	v := Unicode{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	mark_hex := t.viewMark()
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Hex:
				t.viewAppend(cid)
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Hex:
			t.viewAppend(child)
		}
	}
	v._hex = t.viewSlice(mark_hex)
	return v
}

// HexCount returns the number of Hex children.
func (v Unicode) HexCount() int {
	return len(v._hex)
}

// HexAt returns the text of the i-th Hex child.
func (v Unicode) HexAt(i int) string {
	return v.t.Text(v._hex[i])
}

// Value is a read-only view over a Value node.
type Value struct {
	t  *tree
	id NodeID
}

// String returns the full matched text of this node.
func (v Value) String() string {
	return v.t.Text(v.id)
}

// Object returns a Object if this alternative matched.
func (v Value) Object() (Object, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Object) {
		return Object{}, false
	}
	return newObject(v.t, child), true
}

// Array returns a Array if this alternative matched.
func (v Value) Array() (Array, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Array) {
		return Array{}, false
	}
	return newArray(v.t, child), true
}

// StringNode returns a String if this alternative matched.
func (v Value) StringNode() (String, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_String) {
		return String{}, false
	}
	return newString(v.t, child), true
}

// Number returns a Number if this alternative matched.
func (v Value) Number() (Number, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Number) {
		return Number{}, false
	}
	return newNumber(v.t, child), true
}

// IsTrue reports whether this value is the literal "true".
func (v Value) IsTrue() bool {
	child, ok := v.t.Child(v.id)
	if !ok || v.t.Type(child) != NodeType_String {
		return false
	}
	return v.t.Text(child) == "true"
}

// IsFalse reports whether this value is the literal "false".
func (v Value) IsFalse() bool {
	child, ok := v.t.Child(v.id)
	if !ok || v.t.Type(child) != NodeType_String {
		return false
	}
	return v.t.Text(child) == "false"
}

// IsNull reports whether this value is the literal "null".
func (v Value) IsNull() bool {
	child, ok := v.t.Child(v.id)
	if !ok || v.t.Type(child) != NodeType_String {
		return false
	}
	return v.t.Text(child) == "null"
}

// NewJSON creates a JSON view from a parsed tree.
func NewJSON(t Tree) JSON {
	root, ok := t.Root()
	if !ok {
		return JSON{}
	}
	return newJSON(t.(*tree), root)
}
