package extract

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"
	"unicode"
)

const viewsFileTmpl = `// Code generated by langlang extract -mode=views; DO NOT EDIT.
// Grammar: {{.GrammarPath}}

package {{.Package}}

const (
{{- range .NameIDs}}
	_nameID_{{.Name}} int32 = {{.ID}}
{{- end}}
)

{{.Views}}
`

type viewsRenderData struct {
	Package     string
	GrammarPath string
	NameIDs     []NameIDEntry
	Views       string
}

// RenderViewsFile produces a formatted Go source file containing nameID
// constants and zero-allocation view types generated from grammar rules.
func RenderViewsFile(
	pkg, grammarPath string,
	rules map[string]RuleInfo,
	rootRule string,
) (string, error) {
	nameIDs := collectViewNameIDs(rules)
	views := emitViewTypes(rules, rootRule)

	tmpl, err := template.New("views").Parse(viewsFileTmpl)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, viewsRenderData{
		Package:     pkg,
		GrammarPath: grammarPath,
		NameIDs:     nameIDs,
		Views:       views,
	})
	if err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("gofmt: %w (source:\n%s)", err, buf.String())
	}

	return string(formatted), nil
}

// collectViewNameIDs gathers all rules with valid nameIDs for the views file.
func collectViewNameIDs(rules map[string]RuleInfo) []NameIDEntry {
	ordered := orderRules(rules, "")
	var entries []NameIDEntry
	for _, name := range ordered {
		ri := rules[name]
		if ri.NameID >= 0 && unicode.IsUpper(rune(ri.Name[0])) {
			entries = append(entries, NameIDEntry{Name: ri.Name, ID: ri.NameID})
		}
	}
	return entries
}
