file        <- header? record* EOF
header      <- name (COMMA name)* NL
record      <- field (COMMA field)* NL
name        <- field
field       <- escaped / non_escaped
escaped     <- DQUOTE (TEXTDATA / COMMA / CR / LF / D_DQUOTE)* DQUOTE
non_escaped <- TEXTDATA*
COMMA       <- ','
CR          <- '\r'
DQUOTE      <- '"'
LF          <- '\n'
NL          <- CR LF / CR / LF
TEXTDATA    <- ![",\n] .
D_DQUOTE    <- '"' '"'
EOF         <- !.
