// Execute the following command to try this out:
//   RUST_LOG=debug cargo run --bin langlang run --grammar-file tests/shelltest.peg

// Top level production for testing parsing hex numbers with a custom
// error message or a list of emojies
Value <- HexNum / Emoji

// Read hex numbers.  The label hexDigit is there to say that the
// expression labeled with it MUST succeed otherwise an error named
// after the label will be thrown.
HexNum <- '0x' [a-fA-F0-9]+^hexDigit

// We do emojies too, try an animal
Emoji  <- [🦄🐶🐱🐭🐹🐰🦊🐻🐼🐨🐯🦁🐮🐷🐸🐵]
