#!/bin/bash

VERSION=$(git describe --tags --always --dirty)

declare -a suites=("charsets" "import" "json" "langlang")

for suite in "${suites[@]}"; do
  echo "Benchmark $suite"

  TEST_PATH=./tests/${suite}

  if [ -d $TEST_PATH ]; then

      BENCH_PATH=benches/${VERSION}/${suite}
      mkdir -p $BENCH_PATH
      echo "Output path: $BENCH_PATH"

      go test ${TEST_PATH}/... -v -run=^$ \
         -bench=BenchmarkParser\/ -benchmem    \
         -memprofile "${BENCH_PATH}/mem.out"  \
         -cpuprofile "${BENCH_PATH}/cpu.out"  \
         -benchtime 2s -count 15 | tee $BENCH_PATH/txt

      BENCH_PATH_NOCAP=benches/${VERSION}/${suite}_nocap
      mkdir -p $BENCH_PATH_NOCAP
      echo "Output path: $BENCH_PATH_NOCAP"

      go test ${TEST_PATH}/... -v -run=^$ \
         -bench=BenchmarkNoCapParser/ -benchmem     \
         -memprofile "${BENCH_PATH_NOCAP}/mem.out"  \
         -cpuprofile "${BENCH_PATH_NOCAP}/cpu.out"  \
         -benchtime 2s -count 15 | tee $BENCH_PATH_NOCAP/txt

  else
      echo "Don't have the suite ${suite} :("
  fi
done
