// Code generated by langlang extract; DO NOT EDIT.
// Grammar: ../docs/live/assets/examples/json/json.peg

package jsonextract

import "fmt"

var _ = fmt.Errorf

const (
	_nameID_Object int32 = 20
	_nameID_Array  int32 = 21
	_nameID_String int32 = 22
	_nameID_Number int32 = 28
	_nameID_Member int32 = 32
	_nameID_Value  int32 = 18
)

func ExtractJSONValue(t *tree, id NodeID) (JSONValue, error) {
	var out JSONValue
	child, ok := t.Child(id)
	if !ok {
		return out, fmt.Errorf("JSONValue: no child")
	}

	switch {
	case t.IsNamed(child, _nameID_Object):
		val, err := ExtractJSONObject(t, child)
		if err != nil {
			return out, err
		}
		out.Object = &val
	case t.IsNamed(child, _nameID_Array):
		val, err := ExtractJSONArray(t, child)
		if err != nil {
			return out, err
		}
		out.Array = &val
	case t.IsNamed(child, _nameID_String):
		s := t.Text(child)
		out.String = &s
	case t.IsNamed(child, _nameID_Number):
		s := t.Text(child)
		out.Number = &s
	case t.Type(child) == NodeType_String:
		// literal alternative (e.g., 'true', 'false', 'null')
	}
	return out, nil
}

func ExtractJSONObject(t *tree, id NodeID) (JSONObject, error) {
	var out JSONObject
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _nameID_Member:
			val, err := ExtractJSONMember(t, cid)
			if err == nil {
				out.Members = append(out.Members, val)
			}
			return false
		}
		return true
	})
	return out, nil
}

func ExtractJSONMember(t *tree, id NodeID) (JSONMember, error) {
	var out JSONMember
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _nameID_String:
			out.Key = t.Text(cid)
			return false
		case _nameID_Value:
			val, err := ExtractJSONValue(t, cid)
			if err == nil {
				out.Value = val
			}
			return false
		}
		return true
	})
	return out, nil
}

func ExtractJSONArray(t *tree, id NodeID) (JSONArray, error) {
	var out JSONArray
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _nameID_Value:
			val, err := ExtractJSONValue(t, cid)
			if err == nil {
				out.Items = append(out.Items, val)
			}
			return false
		}
		return true
	})
	return out, nil
}
