package parser

import (
	"testing"

	"github.com/stretchr/testify/require"
)

//go:generate go run ../../cmd/langlang -grammar ./tiny.peg -output-language go -output-path ./tiny.go

func TestTiny(t *testing.T) {
	t.Run("Expr", func(t *testing.T) {
		assertExpr(t, "an_id", `Primary (1..6)
└── Id (1..6)
    └── "an_id" (1..6)`)
		assertExpr(t, "12345", `Primary (1..6)
└── Num (1..6)
    └── "12345" (1..6)`)
		assertExpr(t, "(2+34)", `Primary (1..7)
└── Sequence<3> (1..7)
    ├── "(" (1..2)
    ├── Expr (2..6)
    │   └── Sequence<3> (2..6)
    │       ├── Multi (2..3)
    │       │   └── Primary (2..3)
    │       │       └── Num (2..3)
    │       │           └── "2" (2..3)
    │       ├── "+" (3..4)
    │       └── Multi (4..6)
    │           └── Primary (4..6)
    │               └── Num (4..6)
    │                   └── "34" (4..6)
    └── ")" (6..7)`)
		assertExpr(t, "Call()", `Primary (1..7)
└── Call (1..7)
    └── Sequence<3> (1..7)
        ├── Id (1..5)
        │   └── "Call" (1..5)
        ├── "(" (5..6)
        └── ")" (6..7)`)
	})

	t.Run("Call", func(t *testing.T) {
		assertCall(t, "NoParams()", `Call (1..11)
└── Sequence<3> (1..11)
    ├── Id (1..9)
    │   └── "NoParams" (1..9)
    ├── "(" (9..10)
    └── ")" (10..11)`)
		assertCall(t, "OneParam(10)", `Call (1..13)
└── Sequence<4> (1..13)
    ├── Id (1..9)
    │   └── "OneParam" (1..9)
    ├── "(" (9..10)
    ├── Params (10..12)
    │   └── Expr (10..12)
    │       └── Multi (10..12)
    │           └── Primary (10..12)
    │               └── Num (10..12)
    │                   └── "10" (10..12)
    └── ")" (12..13)`)
		assertCall(t, "TwoParams(a, b)", `Call (1..16)
└── Sequence<4> (1..16)
    ├── Id (1..10)
    │   └── "TwoParams" (1..10)
    ├── "(" (10..11)
    ├── Params (11..15)
    │   └── Sequence<4> (11..15)
    │       ├── Expr (11..12)
    │       │   └── Multi (11..12)
    │       │       └── Primary (11..12)
    │       │           └── Id (11..12)
    │       │               └── "a" (11..12)
    │       ├── "," (12..13)
    │       ├── Spacing (13..14)
    │       │   └── " " (13..14)
    │       └── Expr (14..15)
    │           └── Multi (14..15)
    │               └── Primary (14..15)
    │                   └── Id (14..15)
    │                       └── "b" (14..15)
    └── ")" (15..16)`)
		assertCall(t, "ThreeParamsRecurse(a, Rec(x, y), c)", `Call (1..36)
└── Sequence<4> (1..36)
    ├── Id (1..19)
    │   └── "ThreeParamsRecurse" (1..19)
    ├── "(" (19..20)
    ├── Params (20..35)
    │   └── Sequence<7> (20..35)
    │       ├── Expr (20..21)
    │       │   └── Multi (20..21)
    │       │       └── Primary (20..21)
    │       │           └── Id (20..21)
    │       │               └── "a" (20..21)
    │       ├── "," (21..22)
    │       ├── Spacing (22..23)
    │       │   └── " " (22..23)
    │       ├── Expr (23..32)
    │       │   └── Multi (23..32)
    │       │       └── Primary (23..32)
    │       │           └── Call (23..32)
    │       │               └── Sequence<4> (23..32)
    │       │                   ├── Id (23..26)
    │       │                   │   └── "Rec" (23..26)
    │       │                   ├── "(" (26..27)
    │       │                   ├── Params (27..31)
    │       │                   │   └── Sequence<4> (27..31)
    │       │                   │       ├── Expr (27..28)
    │       │                   │       │   └── Multi (27..28)
    │       │                   │       │       └── Primary (27..28)
    │       │                   │       │           └── Id (27..28)
    │       │                   │       │               └── "x" (27..28)
    │       │                   │       ├── "," (28..29)
    │       │                   │       ├── Spacing (29..30)
    │       │                   │       │   └── " " (29..30)
    │       │                   │       └── Expr (30..31)
    │       │                   │           └── Multi (30..31)
    │       │                   │               └── Primary (30..31)
    │       │                   │                   └── Id (30..31)
    │       │                   │                       └── "y" (30..31)
    │       │                   └── ")" (31..32)
    │       ├── "," (32..33)
    │       ├── Spacing (33..34)
    │       │   └── " " (33..34)
    │       └── Expr (34..35)
    │           └── Multi (34..35)
    │               └── Primary (34..35)
    │                   └── Id (34..35)
    │                       └── "c" (34..35)
    └── ")" (35..36)`)
	})

	t.Run("Num", func(t *testing.T) {
		assertNum(t, "12340", `Num (1..6)
└── "12340" (1..6)`)
		assertNum(t, "43210", `Num (1..6)
└── "43210" (1..6)`)
	})

	t.Run("Id", func(t *testing.T) {
		assertId(t, "just_an_id", `Id (1..11)
└── "just_an_id" (1..11)`)
		assertId(t, "_start_with_underscore", `Id (1..23)
└── "_start_with_underscore" (1..23)`)
		assertId(t, "can_have_numbers_1234", `Id (1..22)
└── "can_have_numbers_1234" (1..22)`)
	})
}

func assertExpr(t *testing.T, input, expected string) {
	p := NewParser()
	p.SetInput([]byte(input))
	v, err := p.ParsePrimary()
	require.NoError(t, err)
	require.Equal(t, expected, PrettyString(p.GetInput(), v))
}

func assertCall(t *testing.T, input, expected string) {
	p := NewParser()
	p.SetInput([]byte(input))
	v, err := p.ParseCall()
	require.NoError(t, err)
	require.Equal(t, expected, PrettyString(p.GetInput(), v))
}

func assertNum(t *testing.T, input, expected string) {
	p := NewParser()
	p.SetInput([]byte(input))
	v, err := p.ParseNum()
	require.NoError(t, err)
	require.Equal(t, expected, PrettyString(p.GetInput(), v))
}

func assertId(t *testing.T, input, expected string) {
	p := NewParser()
	p.SetInput([]byte(input))
	v, err := p.ParseId()
	require.NoError(t, err)
	require.Equal(t, expected, PrettyString(p.GetInput(), v))
}
