// Code generated by langlang extract; DO NOT EDIT.
// Grammar: examples/toml-extract/toml.peg

package tomlextract

import "fmt"

var _ = fmt.Errorf

const (
	_nameID_Expression   int32 = 6
	_nameID_Table        int32 = 7
	_nameID_KeyVal       int32 = 16
	_nameID_Key          int32 = 9
	_nameID_Val          int32 = 17
	_nameID_SimpleKey    int32 = 10
	_nameID_BareKey      int32 = 15
	_nameID_BasicString  int32 = 12
	_nameID_InlineTable  int32 = 19
	_nameID_Array        int32 = 20
	_nameID_Number       int32 = 22
	_nameID_Boolean      int32 = 23
	_nameID_DateTime     int32 = 21
	_nameID_InlineKeyVal int32 = 26
)

func ExtractTOMLDoc(t *tree, id NodeID) (TOMLDoc, error) {
	var out TOMLDoc
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _nameID_Expression:
			val, err := ExtractTOMLExpression(t, cid)
			if err == nil {
				out.Expressions = append(out.Expressions, val)
			}
			return false
		}
		return true
	})
	return out, nil
}

func ExtractTOMLExpression(t *tree, id NodeID) (TOMLExpression, error) {
	var out TOMLExpression
	child, ok := t.Child(id)
	if !ok {
		return out, fmt.Errorf("TOMLExpression: no child")
	}

	switch {
	case t.IsNamed(child, _nameID_Table):
		val, err := ExtractTOMLTable(t, child)
		if err != nil {
			return out, err
		}
		out.Table = &val
	case t.IsNamed(child, _nameID_KeyVal):
		val, err := ExtractTOMLKeyVal(t, child)
		if err != nil {
			return out, err
		}
		out.KeyVal = &val
	case t.Type(child) == NodeType_String:
		// literal alternative (e.g., 'true', 'false', 'null')
	}
	return out, nil
}

func ExtractTOMLTable(t *tree, id NodeID) (TOMLTable, error) {
	var out TOMLTable
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _nameID_Key:
			val, err := ExtractTOMLKey(t, cid)
			if err == nil {
				out.Key = val
			}
			return false
		case _nameID_KeyVal:
			val, err := ExtractTOMLKeyVal(t, cid)
			if err == nil {
				out.KeyVals = append(out.KeyVals, val)
			}
			return false
		}
		return true
	})
	return out, nil
}

func ExtractTOMLKeyVal(t *tree, id NodeID) (TOMLKeyVal, error) {
	var out TOMLKeyVal
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _nameID_Key:
			val, err := ExtractTOMLKey(t, cid)
			if err == nil {
				out.Key = val
			}
			return false
		case _nameID_Val:
			val, err := ExtractTOMLVal(t, cid)
			if err == nil {
				out.Val = val
			}
			return false
		}
		return true
	})
	return out, nil
}

func ExtractTOMLKey(t *tree, id NodeID) (TOMLKey, error) {
	var out TOMLKey
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _nameID_SimpleKey:
			val, err := ExtractTOMLSimpleKey(t, cid)
			if err == nil {
				out.SimpleKeys = append(out.SimpleKeys, val)
			}
			return false
		}
		return true
	})
	return out, nil
}

func ExtractTOMLSimpleKey(t *tree, id NodeID) (TOMLSimpleKey, error) {
	var out TOMLSimpleKey
	child, ok := t.Child(id)
	if !ok {
		return out, fmt.Errorf("TOMLSimpleKey: no child")
	}

	switch {
	case t.IsNamed(child, _nameID_BareKey):
		s := t.Text(child)
		out.BareKey = &s
	case t.IsNamed(child, _nameID_BasicString):
		s := t.Text(child)
		out.QuotedKey = &s
	case t.Type(child) == NodeType_String:
		// literal alternative (e.g., 'true', 'false', 'null')
	}
	return out, nil
}

func ExtractTOMLVal(t *tree, id NodeID) (TOMLVal, error) {
	var out TOMLVal
	child, ok := t.Child(id)
	if !ok {
		return out, fmt.Errorf("TOMLVal: no child")
	}

	switch {
	case t.IsNamed(child, _nameID_InlineTable):
		val, err := ExtractTOMLInlineTable(t, child)
		if err != nil {
			return out, err
		}
		out.InlineTable = &val
	case t.IsNamed(child, _nameID_Array):
		val, err := ExtractTOMLArray(t, child)
		if err != nil {
			return out, err
		}
		out.Array = &val
	case t.IsNamed(child, _nameID_BasicString):
		s := t.Text(child)
		out.String = &s
	case t.IsNamed(child, _nameID_Number):
		s := t.Text(child)
		out.Number = &s
	case t.IsNamed(child, _nameID_Boolean):
		s := t.Text(child)
		out.Boolean = &s
	case t.IsNamed(child, _nameID_DateTime):
		s := t.Text(child)
		out.DateTime = &s
	case t.Type(child) == NodeType_String:
		// literal alternative (e.g., 'true', 'false', 'null')
	}
	return out, nil
}

func ExtractTOMLArray(t *tree, id NodeID) (TOMLArray, error) {
	var out TOMLArray
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _nameID_Val:
			val, err := ExtractTOMLVal(t, cid)
			if err == nil {
				out.Items = append(out.Items, val)
			}
			return false
		}
		return true
	})
	return out, nil
}

func ExtractTOMLInlineTable(t *tree, id NodeID) (TOMLInlineTable, error) {
	var out TOMLInlineTable
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _nameID_InlineKeyVal:
			val, err := ExtractTOMLInlineKeyVal(t, cid)
			if err == nil {
				out.KeyVals = append(out.KeyVals, val)
			}
			return false
		}
		return true
	})
	return out, nil
}

func ExtractTOMLInlineKeyVal(t *tree, id NodeID) (TOMLInlineKeyVal, error) {
	var out TOMLInlineKeyVal
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _nameID_Key:
			val, err := ExtractTOMLKey(t, cid)
			if err == nil {
				out.Key = val
			}
			return false
		case _nameID_Val:
			val, err := ExtractTOMLVal(t, cid)
			if err == nil {
				out.Val = val
			}
			return false
		}
		return true
	})
	return out, nil
}
