Program  <- Text* !.
Text     <- Circuit / Expr

Expr     <- Multi (( '+' / '-' ) Multi)*
Multi    <- Primary (( '*' / '/' ) Primary)*
Primary  <- Call / Attr / Port / Id / Num / '(' Expr ')'

Attr     <- Id '.'  (Call / Id / Attr)
Circuit  <- Id '=' Expr
Call     <- Id '(' Params ')'
Params   <- (Expr (',' Expr)*)?
Port     <- Id '[' Num ']'

Num      <- [1-9][0-9]* / '0'
Id       <- [a-zA-Z_][a-zA-Z0-9_]*
